require 'cucumber'
require 'cucumber/rake/task'
require 'rspec/core/rake_task'

desc "Build CoPilot for physical deployment"
task :frankify do

`xcodebuild -target RufusApp -xcconfig /Users/jstewart/rubymineprojects/rufus/rufusapp/frank/frankify.xcconfig -arch armv7 -configuration Debug -sdk iphoneos DEPLOYMENT_LOCATION=YES DSTROOT=\`pwd\`/Frank/Frankified_build FRANK_LIBRARY_SEARCH_PATHS=\`pwd\`/Frank clean build`  

end

desc "Install CoPilot on iPad"
task :fruitstrap do

  Dir.chdir("/Users/jstewart/documents/projects/copilot/frameworks/fruitstrap") do
    
   `./fruitstrap -b /Users/jstewart/Library/Developer/Xcode/DerivedData/RufusApp-bseyccodcsszzhcwbshowgsppecs/Build/Products/Debug-iphoneos/RufusApp.app 2>&1`

  end
end

desc "Start Appium server"
task :appium do

  Dir.chdir("/Users/jstewart/rubymineprojects/rufus/appium") do
      `appium -U 4550a561efc2c047637f342bd6320623ba98c385 --app /Users/jstewart/Library/Developer/Xcode/DerivedData/RufusApp-bseyccodcsszzhcwbshowgsppecs/Build/Products/Debug-iphoneos/RufusApp.app`
  end
end